version: '2'
volumes:
  influxdb-data:
  node-red-data:
services:
  node-red:
    restart: always
    build: ./node-red
    hostname: node-red
    container_name: node-red
    volumes:
      - 'node-red-data:/data'
    privileged: true
    labels:
      io.balena.features.supervisor-api: '1'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    ports:
      - "1880:1880"
      - "502:502"
  influxdb:
    restart: always
    hostname: influxdb
    container_name: influxdb
    build: ./influxdb
    volumes:
      - 'influxdb-data:/data'
  grafana:
    restart: always
    hostname: grafana
    container_name: grafana
    build: ./grafana
    ports:
      - "81:81"
    volumes:
      - 'influxdb-data:/data'
    environment:
        - 'HOME_DASHBOARD_UID=balenaSense'
        - 'GF_PATHS_DATA=/data/grafana'
        - 'GF_SERVER_HTTP_PORT=81'
        - 'GF_SESSION_PROVIDER=memory'
        - 'GF_AUTH_ANONYMOUS_ENABLED=true'
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
