version: '2'
volumes:
  node-red-data:
services:
  node-red:
    restart: always
    build: ./node-red
    hostname: node-red
    container_name: node-red
    volumes:
      - 'node-red-data:/data'
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.kernel-modules: '1'
    cap_add:
      - SYS_RAWIO
      - SYS_MODULE
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    # ports:
    #   - "1880:1880"
    #   - "502:502"
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
